In [3]:
For given a CSV file data.csv:
	1. Create a new DataFrame showing total monthly sales for each customer. Identify customers with consecutive purchases for at least three months.
 
	2. Calculate the quarterly sales for each product and find the product with the highest overall quarterly sales. 
	3. Resample the stock data to a weekly frequency, calculate the average stock price for each week, and identify the week with the highest average price.
	4. Merge the relevant data on EmployeeID and DepartmentID columns to create a new column Total_Salary by summing the Salary for each department.
	
	5. Identify the top 3 sensors with the highest average value, excluding sensors with missing values for more than 10% of the timestamps.
 
Time Duration: 5:30 PM - 6:30 PM
 
Submission Link: Test5

SyntaxError: invalid syntax (3217214706.py, line 1)

In [4]:
import pandas as pd 

df = pd.read_csv("data.csv")
df1 = pd.read_csv("data.csv")
df.head(5)

,CustomerID,ProductID,TransactionDate,SalesAmount,ProductSalesAmount,StockSymbol,StockPrice,SensorID,SensorValue,DepartmentID,EmployeeID,Salary
0,1,101,2023-01-15,150.0,200.0,AAPL,145.50,S1,23.5,D1,E001,5000
1,1,102,2023-02-10,200.0,300.0,MSFT,250.10,S2,25.3,D1,E001,5000
2,2,101,2023-01-20,180.0,150.0,TSLA,650.75,S3,22.8,D2,E002,5500
3,3,103,2023-03-10,120.0,180.0,AAPL,140.20,S1,21.0,D3,E003,4500
4,1,101,2023-03-12,170.0,250.0,AAPL,147.30,S2,26.1,D1,E001,5000

In [5]:
# 	4. Merge the relevant data on EmployeeID and DepartmentID columns to create a new column 'Total_Salary' by summing the Salary for each department.

# df3 = pd.merge(df,df1,left_on="EmployeeID",right_on="DepartmentID")


filt = (df["DepartmentID"] == "D1")
print(df.loc[filt,'Salary'].sum())


filt = (df["DepartmentID"] == "D2")
print(df.loc[filt,'Salary'].sum())


filt = (df["DepartmentID"] == "D3")
print(df.loc[filt,'Salary'].sum())

40900
22000
13500

In [ ]:
Department_data=pd.DataFrame(df.groupby(["DepartmentID"]['EmployeeID']['Salary'].sum())  #grouped the data on the beasis of DepartmentID to calculate the total department salary
# employee_salary=Department_data['Salary'].sum()                     #sliced a particular column from this grouping to get the total sum
# Department_total_salary=employee_salary.sum()                   #performed the task to get total sum
# print(Department_data)
df1=pd.merge(df,Department_data,on="DepartmentID")     
#inner joined the total salary department wise to get the total salary of department in front department employee

#renaming the columns as during inner join names of the salary column got changed
df1.rename(columns={"Salary_x":"Salary","Salary_y":"TotalSalary"},inplace=True)
#printing the DataFrame
df1

IndexError: Column(s) EmployeeID already selected

In [ ]:
Department = pd.data

In [7]:
# 2. Calculate the quarterly sales for each product and find the product with the highest overall quarterly sales. 
df.head()

,CustomerID,ProductID,TransactionDate,SalesAmount,ProductSalesAmount,StockSymbol,StockPrice,SensorID,SensorValue,DepartmentID,EmployeeID,Salary
0,1,101,2023-01-15,150.0,200.0,AAPL,145.50,S1,23.5,D1,E001,5000
1,1,102,2023-02-10,200.0,300.0,MSFT,250.10,S2,25.3,D1,E001,5000
2,2,101,2023-01-20,180.0,150.0,TSLA,650.75,S3,22.8,D2,E002,5500
3,3,103,2023-03-10,120.0,180.0,AAPL,140.20,S1,21.0,D3,E003,4500
4,1,101,2023-03-12,170.0,250.0,AAPL,147.30,S2,26.1,D1,E001,5000

In [8]:

# 1. Create a new DataFrame showing total monthly sales for each customer. Identify customers with consecutive purchases for at least three months.

filt = (df["CustomerID"] == 2 )
print(df.loc[filt,"SalesAmount"].sum())


a = df["TransactionDate"].tolist()
a.sort()
for i in a:
    if '2023-01-01'<i<'2023-02-01':
        filt = (df["CustomerID"] == 1 )
        filt1 = (df["CustomerID"] == 2 )
        filt2 = (df["CustomerID"] == 3 )
        filt3 = (df["CustomerID"] == 4 )
        filt4 = (df["CustomerID"] == 5 )
        filt5 = (df["CustomerID"] == 6 )
        
        
print(df.loc[filt,"SalesAmount"].sum())
print(df.loc[filt1,"SalesAmount"].sum())
print(df.loc[filt2,"SalesAmount"].sum())
print(df.loc[filt3,"SalesAmount"].sum())
print(df.loc[filt4,"SalesAmount"].sum())
print(df.loc[filt5,"SalesAmount"].sum())
# likewise of every month we will calcualte the sum of each customer id

820.0
900.0
820.0
510.0
430.0
600.0
400.0

In [45]:
# 5. Identify the top 3 sensors with the highest average value, excluding sensors with missing values for more than 10% of the timestamps.
df.head()

,CustomerID,ProductID,TransactionDate,SalesAmount,ProductSalesAmount,StockSymbol,StockPrice,SensorID,SensorValue,DepartmentID,EmployeeID,Salary,Total Salary
0,1,101,2023-01-15,150.0,200.0,AAPL,145.50,S1,23.5,D1,E001,5000,105600
1,1,102,2023-02-10,200.0,300.0,MSFT,250.10,S2,25.3,D1,E001,5000,105600
2,2,101,2023-01-20,180.0,150.0,TSLA,650.75,S3,22.8,D2,E002,5500,105600
3,3,103,2023-03-10,120.0,180.0,AAPL,140.20,S1,21.0,D3,E003,4500,105600
4,1,101,2023-03-12,170.0,250.0,AAPL,147.30,S2,26.1,D1,E001,5000,105600

In [58]:
filt = (df["SensorID"] == "S1" )
print(df.loc[filt,"SensorValue"].mean())

filt = (df["SensorID"] == "S2" )
print(df.loc[filt,"SensorValue"].mean())


filt = (df["SensorID"] == "S3" )
print(df.loc[filt,"SensorValue"].mean())

# print("highiest averge :" , print(df.loc[filt,"SensorValue"].mean()))

22.450000000000003
24.816666666666666
24.150000000000002

In [8]:
# 2. Calculate the quarterly sales for each product and find the product with the highest overall quarterly sales. 

df.head()

,CustomerID,ProductID,TransactionDate,SalesAmount,ProductSalesAmount,StockSymbol,StockPrice,SensorID,SensorValue,DepartmentID,EmployeeID,Salary
0,1,101,2023-01-15,150.0,200.0,AAPL,145.50,S1,23.5,D1,E001,5000
1,1,102,2023-02-10,200.0,300.0,MSFT,250.10,S2,25.3,D1,E001,5000
2,2,101,2023-01-20,180.0,150.0,TSLA,650.75,S3,22.8,D2,E002,5500
3,3,103,2023-03-10,120.0,180.0,AAPL,140.20,S1,21.0,D3,E003,4500
4,1,101,2023-03-12,170.0,250.0,AAPL,147.30,S2,26.1,D1,E001,5000

In [18]:
#2 
a = df["TransactionDate"].tolist()
a.sort()
for i in a :
    
    if '2023-01-01'<i<'2023-04-01':
        filt = (df["ProductID"] == 101 )
        filt1 = (df["ProductID"] == 102 )
        filt2 = (df["ProductID"] == 103 )
        filt3 = (df["ProductID"] == 104 )
        filt4 = (df["ProductID"] == 105 )
        filt5 = (df["ProductID"] == 106 )
print(df.loc[filt,"SalesAmount"].sum())
print(df.loc[filt1,"SalesAmount"].sum())
print(df.loc[filt2,"SalesAmount"].sum())
print(df.loc[filt3,"SalesAmount"].sum())
print(df.loc[filt4,"SalesAmount"].sum())
print(df.loc[filt5,"SalesAmount"].sum())a = df["TransactionDate"].tolist()
a.sort()
for i in a :
    
    if '2023-01-01'<i<'2023-04-01':
        filt = (df["ProductID"] == 101 )
        filt1 = (df["ProductID"] == 102 )
        filt2 = (df["ProductID"] == 103 )
        filt3 = (df["ProductID"] == 104 )
        filt4 = (df["ProductID"] == 105 )
        filt5 = (df["ProductID"] == 106 )
print(df.loc[filt,"SalesAmount"].sum())
print(df.loc[filt1,"SalesAmount"].sum())
print(df.loc[filt2,"SalesAmount"].sum())
print(df.loc[filt3,"SalesAmount"].sum())
print(df.loc[filt4,"SalesAmount"].sum())
print(df.loc[filt5,"SalesAmount"].sum())

IndentationError: unexpected indent (4028090343.py, line 21)

In [12]:
	# 5. Identify the top 3 sensors with the highest average value, excluding sensors with missing values for more than 10% of the timestamps.
Sensors = pd.DataFrame(df.groupby(['SensorID'])['SensorValue'].mean(),)
print(Sensors)
Sensors.sort_values(by=['SensorValue'],ascending=False)

          SensorValue
SensorID
S1          22.450000
S2          24.816667
S3          24.150000

          SensorValue
SensorID
S2          24.816667
S3          24.150000
S1          22.450000